services:
  anythingllm1:
    image: mintplexlabs/anythingllm
    container_name: anythingllm1
    restart: unless-stopped
    volumes:
      - /mnt/volume_syd1_02/anythingllm/instance1:/app/server/storage
    environment:
      - STORAGE_DIR=/app/server/storage
    networks:
      - caddy-net

networks:
  caddy-net:
    external: true
