services:
  anythingllm1:
    image: mintplexlabs/anythingllm
    container_name: anythingllm3
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    volumes:
      - /mnt/volume_syd1_02/anythingllm/instance3:/app/server/storage
    environment:
      - STORAGE_DIR=/app/server/storage
    networks:
      - caddy-net

networks:
  caddy-net:
    external: true
